# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with: xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Test
        run: |
          xcodebuild clean test -workspace Shopping-cart.xcworkspace -scheme Shopping-cart -destination 'platform=iOS Simulator,name=iPhone 13' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -allowProvisioningUpdates

